---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import a dataset.

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", " "))
litters_df =
  janitor::clean_names(litters_df)

pups_df =
  read_csv(
    "data_import_examples/FAS_pups.csv", 
    na = c("NA", ".", ""), 
    skip = 3)
pups_df =
  janitor::clean_names(pups_df)
```

## select

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select a range

```{r}
select(litters_df, group:gd_of_birth)
```

select by removal

```{r}
select(litters_df, -group)
select(litters_df, -group:gd_of_birth)
```

select by prefix

```{r}
select(litters_df, group, starts_with("gd"))
```

rearrange by selection
```{r}
select(litters_df, starts_with("gd"), group)
select(litters_df, litter_number, everything())

relocate(litters_df, litter_number)
```

rename by selecting
```{r}
select(litters_df, GROUP = group, everything())
rename(litters_df, GROUP = group)
```

what if i only select one variable

```{r}
select(litters_df, group)

pull(litters_df, group) # will also do the same thing but not as efficient
```

learning assessment

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## filger
use `filter()` to filter out rows.

```{r}
filter(litters_df, gd_of_birth == 20, pups_born_alive == 6)
```

look for more than two pups alive

```{r}
filter(litters_df, pups_born_alive > 5)
filter(litters_df, pups_born_alive >= 5)
filter(litters_df, pups_born_alive <= 5)
```

look for non-matches

```{r}
filter(litters_df, pups_born_alive != 6)
```

match to a set

```{r}
filter(litters_df, group %in% c("Con7", "Con8"))
```

filtering out missing rows with `drop_na()`

```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

learning assessment

```{r}
filter(pups_df, sex == 1)
filter(pups_df, pd_walk < 11, sex == 2)
```


