---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset.

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv")
```

Looking at the data
```{r}
names(litters_df)
```

Update the names in `litters_df`
```{r}
litters_df =
  janitor::clean_names(litters_df)
```

Looking at the data pt. 2
```{r}
litters_df
```

SOmetimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```

## Fix the missingness

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na=c("NA", ".", ""))
```

## Import FAS_pups dataset
```{r}
pups_df =
  read_csv(
    "data_import_examples/FAS_pups.csv", 
    na = c("NA", ".", ""), 
    skip = 3)

pups_df =
  janitor::clean_names(pups_df)
```

## Excel

```{r}
mlb_df =
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LotR word counts
```{r}
fotr_df =
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

## SAS

Import PULSE dataset

```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df =
  janitor::clean_names(pulse_df)
```

## read.csv

```{r, eval = fALSE}
litters_df_base =
  read.csv("Data_import_examples/FAS_litters.csv")

# Messier in comparison to read_csv
```



