---
title: "Tidy data"
output: github_document
date: "2025-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-up

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Pivot longer

```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
    ) %>% 
  mutate(visit = replace(visit, visit =="bl", "00m")) %>% 
  relocate(id, visit)
```

## Pivot longer example 2

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = gd0_weight:gd18_weight, # Columns of interest, integrating the columns into each other
    names_to = "gd_time", # specifies the name of the new column that will be created to store the original column names from the "wide" format data, after they have been pivoted into a "long" format
    values_to = "weight", # gives the name of the variable that will be created from the data stored in the cell value
) %>% 
  mutate(gd_time = case_match(
    gd_time,
    "gd0_weight" ~ 0,
    "gd18_weight" ~ 18
  ))
```

## Pivot wider

```{r}
analysis_df =
  tibble(group = c("treatment", "treatment", "control", "control"),
         time = c("pre", "post", "pre", "post"),
         mean = c(4, 10, 4.2, 4))
```

## Pivot wider with better readability
```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time, # take the names from an existing variable
    values_from = mean # take the values from an existing variable
  ) %>% 
  knitr::kable()
```

## Bind tables

```{r}
fellowship_ring = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
    pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words") %>% 
  relocate(movie) %>% 
  mutate(race = str_to_lower(race))
```



